Fix clEsperanto top_hat_box radius param names
If you copy paste the example code and use radiusX, radiusY, radiusZ (with values) it results in an error:
TypeError: got an unexpected keyword argument 'radiusX'
Changing to radius_x and so on, resolves the error.